[package]
name = "aws_crt_s3_client"
version = "0.1.0"
edition = "2021"
authors = ["Alex Woods <alexwoo@amazon.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }

[build-dependencies]
